# Generated by Django 5.2 on 2025-04-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], max_length=10)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10)),
                ('unit_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
                ('owner', models.ForeignKey(limit_choices_to={'contact_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(max_length=20)),
                ('landlord', models.ForeignKey(limit_choices_to={'contact_type': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_leases', to='core.contact')),
                ('tenant', models.ForeignKey(limit_choices_to={'contact_type': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to='core.contact')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
        ),
    ]
